Repository YAPP-Github/21st-Web-Team-1-FE, pull requests merged in 2022-12, with the labels that each got.

#22 🔧 Fix: storybook cli 에서 deprecated 옵션인 `-s public` 제거
  package.json
Labels: bug, chore

#30 ✨ [YW-75] 버튼 컴포넌트 제작
  public/icon/download.svg
  public/icon/kakao.svg
  public/icon/meatball.svg
  public/icon/profile.svg
  public/icon/share.svg
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Button/button.css
  src/components/common/Button/index.tsx
  src/components/common/Icon/assets.ts
  src/components/common/Icon/index.tsx
  tailwind.config.js
Labels: feature

#35 💄 [YW-67] SideBar 컴포넌트 제작
  .pnp.cjs
  .yarn/cache/@radix-ui-primitive-npm-1.0.0-c47805c644-72996afaf3.zip
  .yarn/cache/@radix-ui-react-accordion-npm-1.0.1-6e3eb2a9eb-fe38705efa.zip
  .yarn/cache/@radix-ui-react-collapsible-npm-1.0.1-c6b12fe32c-24c4611c06.zip
  .yarn/cache/@radix-ui-react-collection-npm-1.0.1-b8a391b409-4922b358ba.zip
  .yarn/cache/@radix-ui-react-compose-refs-npm-1.0.0-ec19c72c12-fb98be2e27.zip
  .yarn/cache/@radix-ui-react-context-npm-1.0.0-3e8c53f3cd-43c6b6f218.zip
  .yarn/cache/@radix-ui-react-id-npm-1.0.0-7738d0781e-ba323cedd6.zip
  .yarn/cache/@radix-ui-react-presence-npm-1.0.0-c2b402211d-a607d67795.zip
  .yarn/cache/@radix-ui-react-primitive-npm-1.0.1-171f608cc7-1cc86b72f9.zip
  .yarn/cache/@radix-ui-react-slot-npm-1.0.1-8752e36473-a20693f8ce.zip
  .yarn/cache/@radix-ui-react-use-callback-ref-npm-1.0.0-1038e8ea02-a8dda76ba0.zip
  .yarn/cache/@radix-ui-react-use-controllable-state-npm-1.0.0-3590acab0b-35f1e714bb.zip
  .yarn/cache/@radix-ui-react-use-layout-effect-npm-1.0.0-4b378f90a5-fcdc8cfa79.zip
  package.json
  public/icon/chevronDown.svg
  src/components/common/Icon/assets.ts
  src/components/common/SideBar/SideBar.stories.tsx
  src/components/common/SideBar/index.tsx
  src/pages/index.tsx
  tailwind.config.js
  yarn.lock
Labels: design

#38 ✨ feat: useLocalStorage 구현
  src/application/hooks/common/index.ts
  src/application/hooks/common/useLocalStorage.ts
  src/application/hooks/index.ts
  src/application/util/.gitkeep
  src/application/util/index.ts
  src/application/util/storage.ts
  src/components/search/SearchItem/index.tsx
  src/pages/search/index.tsx
Labels: feature

#40 ✨ [YW-111] 밈 상세 페이지 사진 및 설명 제작
  .pnp.cjs
  .storybook/preview-head.html
  .storybook/preview.js
  .yarn/cache/@tailwindcss-line-clamp-npm-0.4.2-7e8725ef00-26b8135df2.zip
  mocks/handlers/index.ts
  mocks/handlers/meme/index.ts
  next.config.js
  package.json
  public/icon/warn.svg
  src/application/hooks/api/index.ts
  src/application/hooks/api/meme/index.ts
  src/application/hooks/api/search/index.ts
  src/application/hooks/common/index.ts
  src/application/hooks/common/useDebounce.ts
  src/application/hooks/common/useEllipsis.stories.tsx
  src/application/hooks/common/useEllipsis.ts
  src/components/common/Button/Button.stories.tsx
  src/components/common/Icon/assets.ts
  src/components/common/Photo/Photo.stories.tsx
  src/components/common/Photo/index.tsx
  src/components/meme/detail/MemeDetail.stories.tsx
  src/components/meme/detail/index.tsx
  src/infra/api/index.ts
  src/infra/api/meme.ts
  src/infra/api/search.ts
  src/pages/meme/[id].tsx
  src/types/.gitkeep
  src/types/index.d.ts
  tailwind.config.js
  yarn.lock
Labels: feature

#44 :bug: Fix: storybook 실행 오류 수정 [YW-111]
  .env.development
  .github/workflows/chromatic.yml
  .pnp.cjs
  .storybook/main.js
  .storybook/preview.js
  .yarn/cache/storybook-addon-next-router-npm-4.0.2-4a37bf021d-5e3d1b2510.zip
  .yarn/cache/tslib-npm-2.4.0-9cb6dc5030-8c4aa6a3c5.zip
  package.json
  src/components/meme/detail/MemeDetail.stories.tsx
  yarn.lock
Labels: bug

#48 📦 chore: 새로운 className 추가
  tailwind.config.js
Labels: setting

#50 ✨ [YW-107] 밈 상세페이지 태그 리스트 UI
  mocks/handlers/meme/index.ts
  src/application/hooks/api/meme/index.ts
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Button/IconButton.tsx
  src/components/common/Button/index.ts
  src/components/common/Chip/Chip.stories.tsx
  src/components/common/Chip/Chip.tsx
  src/components/common/Chip/index.ts
  src/components/common/Chip/index.tsx
  src/components/common/Photo/index.tsx
  src/components/meme/MemeDetail/MemeDetail.stories.tsx
  src/components/meme/MemeDetail/MemeDetail.tsx
  src/components/meme/MemeDetail/index.ts
  src/components/meme/MemeShare/MemeShareList.tsx
  src/components/meme/MemeShare/index.ts
  src/components/meme/detail/index.tsx
  src/components/search/SearchItem/index.tsx
  src/components/search/SearchRecent/index.tsx
  src/pages/index.tsx
  src/pages/meme/[id].tsx
  src/styles/globals.css
  src/types/index.d.ts
Labels: feature

#53 :sparkles: Feat: Portal 컴포넌트, useIsMount hook 제작 [YW-127]
  src/application/hooks/common/index.ts
  src/application/hooks/common/useIsMount.ts
  src/components/common/Portal/Portal.tsx
  src/components/common/Portal/index.ts
Labels: feature

#46 ✨ 메인 페이지 및 검색 페이지 UI
  .env.development
  mocks/handlers/index.ts
  mocks/handlers/meme/index.ts
  mocks/handlers/search/index.ts
  mocks/handlers/tags/index.ts
  public/img/Avatar.png
  src/application/hooks/api/index.ts
  src/application/hooks/api/search/index.ts
  src/application/hooks/api/tags/index.ts
  src/application/hooks/domain/search/index.ts
  src/components/home/HomePopular.tsx
  src/components/home/index.ts
  src/components/search/SearchInput/SearchInput.stories.tsx
  src/components/search/SearchInput/SearchInput.tsx
  src/components/search/SearchInput/index.ts
  src/components/search/SearchItem/SearchItem.tsx
  src/components/search/SearchItem/index.ts
  src/components/search/SearchItem/searchItem.stories.tsx
  src/components/search/SearchPopular/SearchPopularItem.tsx
  src/components/search/SearchPopular/SearchPopularList.tsx
  src/components/search/SearchPopular/index.ts
  src/components/search/SearchPopular/index.tsx
  src/components/search/SearchRecent/SearchRecent.tsx
  src/components/search/SearchRecent/index.ts
  src/components/search/SearchResult/SearchResult.tsx
  src/components/search/SearchResult/index.ts
  src/infra/api/index.ts
  src/infra/api/tags.ts
  src/pages/index.tsx
  src/pages/search/index.tsx
  src/types/index.d.ts
Labels: feature, design
