Repository YAPP-Github/21st-Web-Team-1-FE, pull requests merged in 2023-02, with the labels that each got.

#86 ✨ [YW-149] Feat: 인증 로직 재작성
  mocks/handlers/account/index.ts
  mocks/handlers/auth/index.ts
  src/application/hooks/api/account/index.ts
  src/application/hooks/api/account/queryKey.ts
  src/application/hooks/api/index.ts
  src/application/hooks/domain/auth/index.ts
  src/application/hooks/domain/auth/useAuth.ts
  src/application/hooks/domain/index.ts
  src/application/queryClient.tsx
  src/application/util/constant.ts
  src/components/common/Modal/SignUpModal.tsx
  src/components/common/Navigation/Profile/Profile.tsx
  src/components/meme/MemeDetail/Button/KakaoShareButton.tsx
  src/infra/api/account/index.ts
  src/infra/api/account/types.ts
  src/infra/api/auth/index.ts
  src/infra/api/auth/types.ts
  src/infra/api/index.ts
  src/pages/oauth2/redirect/index.tsx
Labels: fix, refactor

#91 💄 [YW-144] 밈 상세페이지 디자인 반영
  .storybook/__mocks__/@next/font.js
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/preview.js
  mocks/handlers/meme/index.ts
  public/icon/collection.svg
  public/icon/memeShare.svg
  public/icon/whiteKakao.svg
  src/application/hooks/common/useDownload.ts
  src/application/util/animation.ts
  src/application/util/index.ts
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/IconButton.tsx
  src/components/common/Button/index.ts
  src/components/common/DropDown/DropDown.tsx
  src/components/common/Icon/assets.ts
  src/components/common/Icon/index.tsx
  src/components/common/Layout/Layout.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/index.ts
  src/components/common/Portal/Portal.tsx
  src/components/common/Toast/Toast.tsx
  src/components/common/Toast/ToastContainer.tsx
  src/components/common/Toast/style.ts
  src/components/common/Toast/types.ts
  src/components/meme/MemeDetail/Button/DownloadButton.tsx
  src/components/meme/MemeDetail/Button/KakaoShareButton.tsx
  src/components/meme/MemeDetail/MemeDetail.tsx
  src/components/meme/MemeDetail/MemeTagList.tsx
  src/components/meme/MemeDetail/index.ts
  src/components/meme/MemeInfo/Button/ClipboardCopyButton.tsx
  src/components/meme/MemeInfo/Button/CollectionSaveButton.tsx
  src/components/meme/MemeInfo/Button/KakaoShareButton.tsx
  src/components/meme/MemeInfo/Button/NativeShareButton.tsx
  src/components/meme/MemeInfo/Button/index.ts
  src/components/meme/MemeInfo/DropDown/MemeExport.tsx
  src/components/meme/MemeInfo/MemeCTAList.tsx
  src/components/meme/MemeInfo/MemeDetail.stories.tsx
  src/components/meme/MemeInfo/MemeDetail.tsx
  src/components/meme/MemeInfo/MemeTagList.tsx
  src/components/meme/MemeInfo/Modal/MemeShareModal.tsx
  src/components/meme/MemeInfo/Modal/index.ts
  src/components/meme/MemeInfo/RelativeMemeList.tsx
  src/components/meme/MemeInfo/index.ts
  src/pages/memes/[id].tsx
  src/styles/fonts/index.ts
  tailwind.config.js
Labels: design

#89 💄[YW-142] 검색 페이지 디자인 반영
  public/icon/delete2.svg
  public/icon/pound.svg
  src/application/hooks/common/useColoredText.tsx
  src/application/hooks/domain/search/index.ts
  src/application/hooks/domain/search/useRecentSearch/index.ts
  src/application/hooks/domain/search/useRecentSearch/types.ts
  src/application/hooks/domain/search/useRecentSearch/useRecentSearch.ts
  src/application/hooks/domain/search/useRecentSearch/utils.ts
  src/components/common/Chip/Chip.tsx
  src/components/common/Icon/assets.ts
  src/components/common/Navigation/CloseButton/CloseButton.tsx
  src/components/common/Navigation/CloseButton/index.ts
  src/components/common/Navigation/SearchPageNavigation.tsx
  src/components/search/SearchInput/SearchInput.tsx
  src/components/search/SearchItem/SearchItem.tsx
  src/components/search/SearchItem/searchItem.stories.tsx
  src/components/search/SearchPopular/SearchPopularItem.tsx
  src/components/search/SearchPopular/SearchPopularList.tsx
  src/components/search/SearchRecent/SearchRecent.tsx
  src/components/search/SearchResult/SearchResultList.tsx
  src/pages/search/index.tsx
  src/types/index.d.ts
Labels: design

#92 💄 [YW-141] 밈 메인 페이지 디자인 반영
  mocks/handlers/tags/index.ts
  public/icon/logo.svg
  public/icon/setting.svg
  src/components/common/Chip/Chip.tsx
  src/components/common/Icon/assets.ts
  src/components/common/Layout/Layout.tsx
  src/components/common/Modal/Modal.stories.tsx
  src/components/common/Modal/ModalBase.tsx
  src/components/common/Modal/ProfileModal.tsx
  src/components/common/Modal/SignUpModal.tsx
  src/components/common/Modal/index.ts
  src/components/common/Navigation/IntroPageNavigation.tsx
  src/components/common/Navigation/Logo/Logo.tsx
  src/components/common/Navigation/Logo/index.ts
  src/components/common/Navigation/Profile/Profile.tsx
  src/components/home/DropDown/MemeSortDropDown.tsx
  src/components/home/PopularTag/PopularTagList.tsx
  src/components/home/SharedMeme/ShareMeme.stories.tsx
  src/components/home/SharedMeme/SharedMemeItem.tsx
  src/components/home/SharedMeme/SharedMemeList.tsx
  src/components/home/SharedMeme/index.ts
  src/components/home/index.ts
  src/pages/index.tsx
  src/pages/search/index.tsx
Labels: design

#90 ✨ [YW-150] Feat: seo 관련 설정
  .pnp.cjs
  .yarn/cache/@corex-deepmerge-npm-4.0.37-de6245d411-f6f5daf297.zip
  .yarn/cache/next-sitemap-npm-3.1.49-95c6592856-bc74ad4a55.zip
  .yarnrc.yml
  next-sitemap.config.js
  package.json
  public/google0f21533cc94d63a5.html
  src/application/util/index.ts
  src/application/util/seo.ts
  src/components/common/NextSeo/NextSeo.tsx
  src/components/common/NextSeo/index.ts
  src/components/common/NextSeo/types.ts
  src/pages/_document.tsx
  src/pages/explore/keywords/index.tsx
  src/pages/explore/tags/index.tsx
  src/pages/index.tsx
  src/pages/memes/[id].tsx
  src/pages/search/index.tsx
  src/pages/sitemap.xml/index.tsx
  yarn.lock
Labels: feature

#96 💄 에러 페이지 & 일부 스타일 이슈 수정
  src/components/common/Accordion/Accordion.tsx
  src/components/common/Chip/Chip.tsx
  src/components/common/Drawer/Drawer.tsx
  src/components/common/Error/GlobalError.tsx
  src/components/common/Error/index.ts
  src/components/common/ErrorBoundary/QueryErrorBoundary.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Navigation/Navigation.tsx
  src/components/common/Navigation/SideBar/SideBar.tsx
  src/components/common/Portal/Portal.tsx
  src/components/home/PopularTag/PopularTagList.tsx
  src/components/meme/MemeInfo/Button/NativeShareButton.tsx
  src/components/meme/MemeInfo/DropDown/MemeExport.tsx
  src/components/meme/MemeInfo/MemeDetail.tsx
  src/components/meme/MemeInfo/Modal/MemeShareModal.tsx
  src/components/meme/MemeInfo/RelativeMemeList.tsx
  src/components/search/SearchInput/SearchInput.tsx
  src/pages/_app.tsx
  src/pages/_error.tsx
  src/pages/index.tsx
  src/pages/search/index.tsx
  src/styles/globals.css
Labels: fix, design

#98 ✨ 액션시트 라이브러리 추가
  .pnp.cjs
  .yarn/cache/konsta-npm-1.0.2-5e9389ba38-b582961e04.zip
  package.json
  src/application/util/device.ts
  src/application/util/index.ts
  src/components/common/LongPress/LongPress.tsx
  src/components/common/LongPress/index.ts
  src/components/common/Modal/Modal.tsx
  src/components/common/Navigation/Navigation.tsx
  src/components/meme/LongPress/MemeLongPress.tsx
  src/components/meme/LongPress/index.ts
  src/components/meme/MemeItem/MemeItem.tsx
  src/components/meme/MemeLongPress/MemeLongPress.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/styles/globals.css
  src/types/index.d.ts
  tailwind.config.js
  yarn.lock
Labels: design

#102 🍀 모달 컴포넌트 리팩토링 & 자잘한 UI 버그 수정
  src/components/common/DropDown/DropDown.tsx
  src/components/common/Modal/Modal.stories.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/ProfileModal.tsx
  src/components/common/Modal/SignUpModal.tsx
  src/components/common/Navigation/Profile/Profile.tsx
  src/components/explore/EmptyMemesView/EmptyMemesView.tsx
  src/components/home/DropDown/MemeSortDropDown.tsx
  src/components/meme/MemeInfo/Button/NativeShareButton.tsx
  src/components/meme/MemeInfo/DropDown/MemeExport.tsx
  src/components/meme/MemeInfo/MemeCTAList.tsx
  src/components/meme/MemeInfo/MemeDetail.tsx
  src/components/meme/MemeInfo/Modal/MemeShareModal.tsx
  src/styles/globals.css
Labels: fix, refactor

#100 ✨ 사이드바 UI 수정 & 즐겨찾기 삭제 로직
  mocks/handlers/search/index.ts
  mocks/handlers/tags/index.ts
  public/icon/cancel.svg
  src/application/hooks/api/tags/index.ts
  src/application/hooks/common/useToast.ts
  src/components/common/Accordion/Accordion.stories.tsx
  src/components/common/Accordion/Accordion.tsx
  src/components/common/Accordion/index.ts
  src/components/common/Navigation/SideBar/Category.stories.tsx
  src/components/common/Navigation/SideBar/Category.tsx
  src/components/common/Navigation/SideBar/SideBar.tsx
  src/components/common/Toast/ToastContainer.tsx
  src/components/common/Toast/style.ts
  src/infra/api/tags/index.ts
  src/infra/api/tags/types.ts
Labels: feature, design

#107 ✨ feat: 태그 즐겨찾기 추가/삭제 API 연동
  .storybook/preview-head.html
  mocks/handlers/tags/data.ts
  mocks/handlers/tags/index.ts
  public/icon/star.svg
  src/application/hooks/api/core/types.ts
  src/application/hooks/api/tags/index.ts
  src/application/hooks/api/tags/queryKey.ts
  src/application/util/image-util.ts
  src/application/util/index.ts
  src/application/util/path.ts
  src/components/common/Icon/assets.ts
  src/components/common/Layout/Layout.tsx
  src/components/common/Navigation/ExplorePageNavigation.tsx
  src/components/common/Navigation/SideBar/Category.tsx
  src/components/common/Photo/Photo.tsx
  src/components/common/Portal/Portal.tsx
  src/components/common/WithAuthHandlers/WithAuthHandlers.tsx
  src/components/common/WithAuthHandlers/index.ts
  src/components/home/PopularTag/PopularTagList.tsx
  src/components/home/UserSharedMeme/SharedMemeItem.tsx
  src/components/meme/MemeInfo/MemeTagList.tsx
  src/components/meme/MemeItem/MemeItem.tsx
  src/components/search/SearchPopular/SearchPopularList.tsx
  src/components/search/SearchRecent/SearchRecent.tsx
  src/components/search/SearchResult/SearchResultList.tsx
  src/components/tags/TagFavoriteButton/TagBookmarkButton.tsx
  src/components/tags/TagFavoriteButton/TagFavoriteButton.tsx
  src/components/tags/TagFavoriteButton/index.ts
  src/infra/api/tags/index.ts
  src/infra/api/tags/types.ts
  src/pages/explore/tags/[tagId].tsx
  src/pages/explore/tags/index.tsx
  src/styles/fonts/index.ts
  src/styles/globals.css
  tailwind.config.js
Labels: feature, design

#101 Feat: 마이페이지, 나의 콜렉션 페이지 API 및 디자인
  mocks/handlers/collection/index.ts
  mocks/handlers/meme/index.ts
  mocks/handlers/search/data.ts
  mocks/handlers/search/index.ts
  src/application/hooks/api/collection/index.ts
  src/application/hooks/api/collection/queryKey.ts
  src/application/hooks/api/index.ts
  src/application/hooks/api/search/index.ts
  src/application/hooks/api/search/queryKey.ts
  src/application/hooks/domain/collection/index.ts
  src/application/hooks/domain/collection/useCollection.ts
  src/application/hooks/domain/index.ts
  src/components/collect/Collection/Collection.tsx
  src/components/collect/Collection/index.ts
  src/components/collect/SearchedCollection/SearchedCollection.tsx
  src/components/collect/SearchedCollection/index.ts
  src/components/collect/index.ts
  src/components/common/Icon/index.tsx
  src/components/common/Layout/Layout.tsx
  src/components/common/Modal/ProfileModal.tsx
  src/components/common/Navigation/ExplorePageNavigation.tsx
  src/components/common/Navigation/MyPageNavigation.tsx
  src/components/common/Navigation/SideBar/SideBar.tsx
  src/components/common/Navigation/index.ts
  src/components/common/Skeleton/Skeleton.tsx
  src/components/hocs/index.ts
  src/components/hocs/withAuth/index.ts
  src/components/hocs/withAuth/withAuth.tsx
  src/components/home/MemeListContainer/MemeList/CommonMemeList.tsx
  src/components/home/MemeListContainer/MemeList/UserFindMemeList.tsx
  src/components/home/PopularTag/PopularTagList.tsx
  src/components/meme/LongPress/MemeLongPress.tsx
  src/components/meme/MemeInfo/Button/CollectionSaveButton.tsx
  src/components/meme/MemeInfo/Button/index.ts
  src/components/meme/MemeInfo/DropDown/MemeExport.tsx
  src/components/meme/MemeInfo/MemeCTAList.tsx
  src/components/meme/MemeInfo/MemeDetail.tsx
  src/components/mypage/SummarizedCollection/SummarizedCollection.tsx
  src/components/mypage/SummarizedCollection/index.ts
  src/components/mypage/index.ts
  src/components/search/SearchInput/SearchInput.tsx
  src/components/share/SharedMemeList.tsx
  src/infra/api/account/types.ts
  src/infra/api/collection/index.ts
  src/infra/api/collection/types.ts
  src/infra/api/meme/index.ts
  src/infra/api/meme/types.ts
  src/infra/api/search/index.ts
  src/pages/_error.tsx
  src/pages/collect/index.tsx
  src/pages/explore/tags/[tagId].tsx
  src/pages/index.tsx
  src/pages/memes/[id].tsx
  src/pages/mypage/index.tsx
  src/pages/search/index.tsx
  src/pages/share/index.tsx
  src/types/index.d.ts
Labels: feature, design

#117 🍀 액션시트 UI 재구현 & 롱프레스 UI 버그 수정
  .pnp.cjs
  .yarn/cache/@babel-runtime-npm-7.21.0-c4ef698c89-7b33e25bfa.zip
  .yarn/cache/@types-react-transition-group-npm-4.4.5-8f92107b07-265f1c7406.zip
  .yarn/cache/dom-helpers-npm-5.2.1-b38bb4470b-863ba9e086.zip
  .yarn/cache/konsta-npm-1.0.2-5e9389ba38-b582961e04.zip
  .yarn/cache/react-transition-group-npm-4.4.5-98ea4ef96e-7560284010.zip
  package.json
  src/application/hooks/api/collection/index.ts
  src/application/hooks/common/useLongPress/index.ts
  src/application/hooks/domain/collection/useCollection.ts
  src/components/collect/Collection/Collection.tsx
  src/components/collect/SearchedCollection/SearchedCollection.tsx
  src/components/common/ActionSheet/ActionSheet.tsx
  src/components/common/ActionSheet/index.ts
  src/components/common/Modal/Modal.tsx
  src/components/common/Overlay/Overlay.tsx
  src/components/common/Overlay/index.ts
  src/components/common/Portal/Portal.tsx
  src/components/explore/MemesByKeyword/MemesByKeyword.tsx
  src/components/explore/MemesByTag/MemesByTag.tsx
  src/components/home/MemeListContainer/MemeList/CommonMemeList.tsx
  src/components/home/MemeListContainer/MemeList/UserFindMemeList.tsx
  src/components/meme/InfiniteMemeList/InfiniteMemeList.tsx
  src/components/meme/LongPress/MemeLongPress.tsx
  src/components/meme/LongPress/MemeLongPressContainer.tsx
  src/components/meme/MemeInfo/RelativeMemeList.tsx
  src/components/meme/MemeItem/MemeItem.tsx
  src/components/share/SharedMemeList.tsx
  src/pages/_app.tsx
  tailwind.config.js
  yarn.lock
Labels: fix, refactor
