Repository YAPP-Github/21st-Web-Team-1-FE, pull requests merged in 2023-01, with the labels that each got.

#54 ✨ [YW-127] 토스트 컴포넌트 개발
  .storybook/preview.js
  mocks/index.ts
  next.config.js
  public/icon/cake.svg
  src/application/hooks/common/index.ts
  src/application/hooks/common/useIsomorphicLayoutEffect.ts
  src/application/hooks/common/useToast.ts
  src/application/util/index.ts
  src/application/util/time.ts
  src/components/common/Icon/assets.ts
  src/components/common/Icon/index.tsx
  src/components/common/Toast/Toast.stories.tsx
  src/components/common/Toast/Toast.tsx
  src/components/common/Toast/ToastContainer.tsx
  src/components/common/Toast/context.tsx
  src/components/common/Toast/index.ts
  src/components/common/Toast/types.ts
  src/components/meme/MemeShare/MemeShareList.tsx
  src/pages/_app.tsx
  tailwind.config.js
  tsconfig.json
Labels: feature, design

#52 ✨ 모달 컴포넌트
  public/icon/google.svg
  public/icon/kakao2.svg
  public/img/brandimage.png
  public/img/signup.png
  src/application/hooks/common/index.ts
  src/application/hooks/common/useClickOutside.ts
  src/application/hooks/common/useModal.ts
  src/components/common/Icon/assets.ts
  src/components/common/Modal/Modal.stories.tsx
  src/components/common/Modal/ModalBase.tsx
  src/components/common/Modal/SampleModal.tsx
  src/components/common/Modal/index.ts
  src/pages/index.tsx
Labels: feature, design

#60 💄 바뀐 디자인 시스템 적용 & 기존 스타일 제거
  src/application/hooks/common/useColoredText.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Chip/Chip.tsx
  src/components/common/Icon/index.tsx
  src/components/common/Navigation/index.tsx
  src/components/common/Photo/Photo.stories.tsx
  src/components/common/SideBar/index.tsx
  src/components/search/SearchItem/SearchItem.tsx
  src/pages/index.tsx
  src/pages/meme/[id].tsx
  src/pages/search/index.tsx
  tailwind.config.js
Labels: design

#49 ✨ [YW-104] 밈 검색 결과 페이지(twin.macro 적용, Masonry 컴포넌트, 무한스크롤)
  .pnp.cjs
  .storybook/__mocks__/next/link.js
  .storybook/main.js
  .yarn/cache/@babel-parser-npm-7.20.7-3710a9bc4f-25b5266e3b.zip
  .yarn/cache/@babel-runtime-npm-7.20.7-69d8df458c-4629ce5c46.zip
  .yarn/cache/@babel-template-npm-7.20.7-c157fc5838-2eb1a0ab8d.zip
  .yarn/cache/@babel-types-npm-7.20.7-8dc703d95e-b39af241f0.zip
  .yarn/cache/@emotion-babel-plugin-npm-11.10.5-8dcb672ed0-e3353499c7.zip
  .yarn/cache/@emotion-cache-npm-11.10.5-e5bc83f178-1dd2d9af2d.zip
  .yarn/cache/@emotion-css-npm-11.10.5-9f9b1c91d1-2f1e953c35.zip
  .yarn/cache/@emotion-hash-npm-0.9.0-efbc0b3f3f-b63428f7c8.zip
  .yarn/cache/@emotion-is-prop-valid-npm-1.2.0-332d343e3d-cc7a19850a.zip
  .yarn/cache/@emotion-memoize-npm-0.8.0-c5dd451828-c87bb110b8.zip
  .yarn/cache/@emotion-react-npm-11.10.5-98e2cdb553-32b67b28e9.zip
  .yarn/cache/@emotion-serialize-npm-1.1.1-b082a29d71-24cfd5b16e.zip
  .yarn/cache/@emotion-server-npm-11.10.0-4c64a8cb41-15b7135a57.zip
  .yarn/cache/@emotion-sheet-npm-1.2.1-ede8a680b2-ce78763588.zip
  .yarn/cache/@emotion-styled-npm-11.10.5-ff28c219a9-1cec5f6aeb.zip
  .yarn/cache/@emotion-unitless-npm-0.8.0-aa125284fa-176141117e.zip
  .yarn/cache/@emotion-use-insertion-effect-with-fallbacks-npm-1.0.0-d02a7659c4-4f06a3b482.zip
  .yarn/cache/@emotion-utils-npm-1.2.0-337992f692-55457a49dd.zip
  .yarn/cache/@emotion-weak-memoize-npm-0.3.0-705bdd075b-f43ef4c8b7.zip
  .yarn/cache/babel-plugin-twin-npm-1.1.0-b9a1f62558-1e4544ebb1.zip
  .yarn/cache/buffer-from-npm-0.1.2-bc1c3e2819-50a1fa5da9.zip
  .yarn/cache/duplexer2-npm-0.1.4-6bca6bef12-744961f03c.zip
  .yarn/cache/find-root-npm-1.1.0-a16a94005f-b2a59fe4b6.zip
  .yarn/cache/hoist-non-react-statics-npm-3.3.2-e7b709e6c1-b153827042.zip
  .yarn/cache/html-tokenize-npm-2.0.1-5a0e21cce5-4e04078fd2.zip
  .yarn/cache/isarray-npm-0.0.1-92e37e0a70-49191f1425.zip
  .yarn/cache/lodash.get-npm-4.4.2-7bda64ed87-e403047ddb.zip
  .yarn/cache/multipipe-npm-1.0.2-788a149603-99cf893471.zip
  .yarn/cache/object-keys-npm-0.4.0-040f043796-1be3ebe9b4.zip
  .yarn/cache/readable-stream-npm-1.0.34-db63158f3f-85042c537e.zip
  .yarn/cache/string_decoder-npm-0.10.31-851f3f7302-fe00f8e303.zip
  .yarn/cache/stylis-npm-4.1.3-c3e2662f97-d04dbffcb9.zip
  .yarn/cache/through2-npm-0.4.2-6dd450f0d9-50e41d272d.zip
  .yarn/cache/twin.macro-npm-3.1.0-e450f592de-716695be03.zip
  .yarn/cache/xtend-npm-2.1.2-5342807e9c-a8b79f3150.zip
  mocks/handlers/search/index.ts
  next.config.js
  package.json
  public/icon/memeShare.svg
  src/application/hooks/api/search/index.ts
  src/application/hooks/common/index.ts
  src/application/hooks/common/useIntersect.ts
  src/components/common/Icon/assets.ts
  src/components/common/Masonry/Masonry.stories.tsx
  src/components/common/Masonry/Masonry.tsx
  src/components/common/Masonry/index.ts
  src/components/common/Navigation/index.tsx
  src/components/meme/MemeItem/MemeItem.tsx
  src/components/meme/MemeItem/index.ts
  src/infra/api/search.ts
  src/pages/explore/keywords/index.tsx
  src/pages/explore/tags/index.tsx
  src/types/index.d.ts
  yarn.lock
Labels: feature, design

#67 ✨ 밈 상세페이지 API 연동
  mocks/handlers/meme/index.ts
  src/application/hooks/common/useDownload.ts
  src/components/common/Navigation/index.tsx
  src/components/common/Photo/index.tsx
  src/components/meme/MemeDetail/MemeDetail.tsx
  src/infra/api/meme.ts
  src/pages/memes/[id].tsx
  src/types/index.d.ts
  tsconfig.json
Labels: feature

#73 ♻️ MVP 1차 이슈 처리 (프로젝트 설계)
  .pnp.cjs
  mocks/handlers/meme/index.ts
  mocks/handlers/search/data.ts
  mocks/handlers/search/index.ts
  package.json
  src/application/hooks/api/meme/index.ts
  src/application/hooks/api/meme/queryKey.ts
  src/application/hooks/api/search/index.ts
  src/application/hooks/api/search/queryKey.ts
  src/application/hooks/api/tags/index.ts
  src/application/hooks/api/tags/queryKey.ts
  src/components/common/Masonry/Masonry.stories.tsx
  src/components/common/Photo/index.tsx
  src/components/home/HomePopular.tsx
  src/components/meme/MemeDetail/MemeDetail.tsx
  src/components/meme/MemeItem/MemeItem.tsx
  src/components/search/SearchItem/SearchItem.tsx
  src/components/search/SearchItem/searchItem.stories.tsx
  src/components/search/SearchPopular/SearchPopularList.tsx
  src/components/search/SearchResult/SearchResult.tsx
  src/infra/api/client.ts
  src/infra/api/index.ts
  src/infra/api/meme.ts
  src/infra/api/meme/index.ts
  src/infra/api/meme/types.ts
  src/infra/api/search/index.ts
  src/infra/api/search/types.ts
  src/infra/api/tags.ts
  src/infra/api/tags/index.ts
  src/infra/api/tags/types.ts
  src/pages/explore/keywords/index.tsx
  src/pages/explore/tags/index.tsx
  src/types/index.d.ts
  src/types/twin.d.ts
  tsconfig.json
  yarn.lock
Labels: feature, setting

#72 ✨ 네비게이션 스타일 수정 & 사이드바 삽입
  mocks/handlers/tags/index.ts
  package.json
  src/application/hooks/api/tags/index.ts
  src/application/hooks/api/tags/queryKey.ts
  src/application/hooks/common/useToast.ts
  src/components/common/Accordion/Accordion.stories.tsx
  src/components/common/Accordion/Accordion.tsx
  src/components/common/Accordion/index.ts
  src/components/common/Drawer/Drawer.tsx
  src/components/common/Drawer/context.tsx
  src/components/common/Drawer/index.ts
  src/components/common/Layout/Layout.tsx
  src/components/common/Layout/context.tsx
  src/components/common/Layout/index.ts
  src/components/common/Layout/index.tsx
  src/components/common/Navigation/BackButton/BackButton.tsx
  src/components/common/Navigation/BackButton/index.ts
  src/components/common/Navigation/ExplorePageNavigation.tsx
  src/components/common/Navigation/IntroPageNavigation.tsx
  src/components/common/Navigation/Navigation.stories.tsx
  src/components/common/Navigation/Navigation.tsx
  src/components/common/Navigation/Profile/Profile.tsx
  src/components/common/Navigation/Profile/index.ts
  src/components/common/Navigation/SearchPageNavigation.tsx
  src/components/common/Navigation/SideBar/Category.tsx
  src/components/common/Navigation/SideBar/SideBar.stories.tsx
  src/components/common/Navigation/SideBar/SideBar.tsx
  src/components/common/Navigation/SideBar/index.ts
  src/components/common/Navigation/index.ts
  src/components/common/Navigation/index.tsx
  src/components/common/SideBar/SideBar.stories.tsx
  src/components/common/SideBar/index.tsx
  src/components/common/Toast/Toast.stories.tsx
  src/components/common/Toast/Toast.tsx
  src/components/common/Toast/ToastContainer.tsx
  src/components/common/Toast/context.tsx
  src/infra/api/tags/index.ts
  src/infra/api/tags/types.ts
  src/pages/explore/keywords/index.tsx
  src/pages/explore/tags/index.tsx
  src/pages/index.tsx
  src/pages/memes/[id].tsx
  src/pages/search/index.tsx
  src/styles/globals.css
Labels: feature, design

#77 ✨ feat: 검색 결과 없을 때 검색 결과 페이지 렌더링
  .env.development
  public/img/emptyAvatar.png
  src/application/hooks/api/search/index.ts
  src/components/common/Navigation/SearchPageNavigation.tsx
  src/components/common/Photo/index.tsx
  src/pages/explore/keywords/index.tsx
  src/pages/explore/tags/index.tsx
Labels: feature

#85 ✨ feat: 폰트, 색상 추가 [YW-146]
  .storybook/preview-head.html
  .storybook/preview.js
  src/components/common/Layout/Layout.tsx
  src/styles/fonts/SUIT-Variable.woff2
  tailwind.config.js
Labels: setting, design
